parserproject:
  # Supports relative/absolute folders, network shares, s3://bucket/prefix, or azure://container/prefix
  inputFilelocation: ./input/
  algFileNameStartCharcter: ALG-BP-
  dsFileNameStartCharacter: DS-BP-
  rcFileNameStartCharcter : RC-BP-
  containerlocation: ./output/
  yamlTemplateText: 187
  yamlSchemaversion: 0.3
  rateTableFolderName: rate_tables
  #resProjectLocation: C:/Users/renji/OneDrive/Documents/git/rating/RES-Service/
  resProjectLocation: ./output/
#  ercPackageDetails:  C:/Users/renji/OneDrive/Documents/git/rating/RES-Service/input/
  ercPackageDetails: ./input/
  stateContainerLocation: ./output/children/
  version: "01012026"
  lobName: BOP
  algFileNameState: ALG-BP-AL-01012026-V01_MR.xml
  algFileNameCw: ALG-BP-CW-07012025-V01_MR.xml
  dsFileName: DS-BP-AL-01012026-V01.xml
  rcFileName: RC-BP-CW-07012025-V01.xml
  rcFileNameState: RC-BP-AL-01012026-V01.xml
  projectType: JAVA
  coverageAvailabiltyFileName: CoverageAvailability.xlsx
  commonConfigFile: CommonConfig.json
  convertedCalculations: ConvertedCalculations.json
  s3:
    region: ""
    profile: ""
    endpointOverride: ""
  azure:
    connectionString: ""
